name: Deploy to Simply.com via FTP

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to Simply.com (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}     # linux26.unoeuro.com
          username: ${{ secrets.FTP_USERNAME }} # picturesque.dk
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}   # /public_html
          protocol: ftp
          port: 21
          state-name: .ftp-deploy-sync-state.json
          local-dir: ./
          log-level: verbose
          timeout: 60000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
